
-- Programmers: 5월 식품들의 총매출 조회하기
SELECT o.PRODUCT_ID, p.PRODUCT_NAME, SUM(p.PRICE * o.AMOUNT) as TOTAL_SALES
FROM FOOD_ORDER AS o 
JOIN FOOD_PRODUCT AS p on o.PRODUCT_ID = p.PRODUCT_ID
WHERE YEAR(o.PRODUCE_DATE) = 2022 AND MONTH(o.PRODUCE_DATE) = 5
GROUP BY o.PRODUCT_ID, p.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, o.PRODUCT_ID ASC;

-- Programmers: 보호소에서 중성화한 동물
SELECT i.ANIMAL_ID, i.ANIMAL_TYPE, i.NAME 
FROM ANIMAL_INS as i
JOIN ANIMAL_OUTS as o on i.ANIMAL_id = o.ANIMAL_id
WHERE i.SEX_UPON_INTAKE IN ('Intact Male', 'Intact Female') AND 
o.SEX_UPON_OUTCOME IN ('Spayed Male', 'Spayed Female', 'Neutered Male', 'Neutered Female')
ORDER BY i.ANIMAL_ID ASC;

-- Programmers:자동차 대여 기록에서 대여중 / 대여 가능 여부 구분하기
SELECT CAR_ID, 
CASE
    WHEN MAX('2022-10-16' BETWEEN START_DATE AND END_DATE)=1 THEN '대여중'
    ELSE '대여 가능'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC