-- Q1.
SELECT 
    A.PRODUCT_ID, 
    A.PRODUCT_NAME, 
    sum(A.PRICE * B.AMOUNT) as TOTAL_SALES 
FROM FOOD_PRODUCT as A
    INNER JOIN FOOD_ORDER as B on A.PRODUCT_ID = B.PRODUCT_ID
WHERE B.PRODUCE_DATE BETWEEN '2022-05-01' and '2022-05-31'
GROUP BY A.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID ASC

-- Q2
SELECT 
    I.ANIMAL_ID,
    I.ANIMAL_TYPE,
    I.NAME
FROM ANIMAL_INS as I
    INNER JOIN ANIMAL_OUTS as O on I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE IN ('Intact Male', 'Intact Female')
    and O.SEX_UPON_OUTCOME IN ('Neutered Male', 'Spayed Female')
ORDER BY I.ANIMAL_ID ASC

/*
SELECT 
    I.ANIMAL_ID,
    I.ANIMAL_TYPE,
    I.NAME
FROM ANIMAL_INS as I
    INNER JOIN ANIMAL_OUTS as O on I.ANIMAL_ID = O.ANIMAL_ID
WHERE (I.SEX_UPON_INTAKE = 'Intact Male' or I.SEX_UPON_INTAKE = 'Intact Female')
    and (O.SEX_UPON_OUTCOME = 'Neutered Male' or O.SEX_UPON_OUTCOME = 'Spayed Female')
ORDER BY I.ANIMAL_ID ASC
*/

-- Q3
SELECT 
    H.CAR_ID,
    MAX(If (H.START_DATE <= '2022-10-16' and H.END_DATE >= '2022-10-16', 
        '대여중', '대여 가능') )
        as AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY as H
GROUP BY H.CAR_ID
ORDER BY H.CAR_ID DESC
        