<민경>
Q1
SELECT 
    P.PRODUCT_ID, 
    P.PRODUCT_NAME, 
    SUM(P.PRICE * O.AMOUNT) AS TOTAL_SALES
FROM 
    FOOD_PRODUCT P
JOIN 
    FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE 
    DATE_FORMAT(O.PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY 
    P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY 
    TOTAL_SALES DESC, P.PRODUCT_ID ASC;
    


Q2
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE LIKE 'Intact%'
  AND (O.SEX_UPON_OUTCOME LIKE 'Spayed%' OR O.SEX_UPON_OUTCOME LIKE 'Neutered%')
ORDER BY I.ANIMAL_ID;



Q3
SELECT CAR_ID,
CASE 
WHEN MAX('2022-10-16' BETWEEN START_DATE AND END_DATE)=1 THEN '대여중'
ELSE '대여 가능'
END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;